### ISSUE TITLE
JQTIPlus Test failures while building - abrommelhoff/qtiworks fork

### ISSUE THREAD

**Issue by aboudzakaria** [davemckain/qtiworks#66]
I don't know if this is the right place to put this but I'm facing problems while doing a clean install to the project after cloning from abrommelhoff's fork.

details:

    -------------------------------------------------------------------------------
    Test set: uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest
    -------------------------------------------------------------------------------
    Tests run: 8, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.834 sec <<< FAILURE! - in uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest
    testLookupRootNodeWithAccessibilityInclusionOrderApipCore(uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest)  Time elapsed: 1.121 sec  <<< ERROR!
    java.lang.NullPointerException: null
        at uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest.testLookupRootNodeWithAccessibilityInclusionOrderApipCore(QtiObjectReaderTest.java:157)
    
    testLookupRootNodeWithAccessibilityAccessElementsContentLinks(uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest)  Time elapsed: 0.389 sec  <<< ERROR!
    java.lang.NullPointerException: null
        at uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest.testLookupRootNodeWithAccessibilityAccessElementsContentLinks(QtiObjectReaderTest.java:324)
    
    testLookupRootNodeWithAccessibilityInclusionOrder(uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest)  Time elapsed: 0.264 sec  <<< ERROR!
    java.lang.NullPointerException: null
        at uk.ac.ed.ph.jqtiplus.reading.QtiObjectReaderTest.testLookupRootNodeWithAccessibilityInclusionOrder(QtiObjectReaderTest.java:126)

**Comment by davemckain** [comment]
Thanks for the issue report.

I'm afraid I'm not familiar with this fork - it looks like they're adding support for APIP, which sounds nice. I'd suggest contacting abrommelhoff in the first instance to see if they can help resolve the issue.

You may also want to ignore the tests for now if you're feeling brave! (Pass the -Dmaven.test.skip option to maven skip the tests.)
