### ISSUE TITLE
QTI Instance run on jetty failed

### ISSUE THREAD

**Issue by blpraveen** [davemckain/qtiworks#68]
I could not deploy the QTI Engine on a Jetty Server.
I am using eclipse IDE on windows
I downloaded the qtiworks from the github repository and build maven project. It generated  jar files in taget folder.

Then my next step was to run on server . I am getting errors. I have set the config file.

Is it possible to get code of qti engine running on jetty.?

**Comment by davemckain** [comment]
Hi there,

I haven't tried running QTIWorks on Jetty, but would imagine it is roughly the same as Tomcat. You really need to do two things:

(1) Somehow pass the built webapp (qtiworks-engine.war) to Jetty.

(2) Pass "context parameters" to Jetty telling it where to find your QTIWorks config file (qtiworks-deployment.properties) and, optionally, your logging configuration.

Step (2) is likely to be the more complicated part, so you'll need to refer to the Jetty instructions for that. If you can't work this one out, another approach might be for you to add <context-param> elements directly into qtiworks-engine/src/main/webapp/WEB-INF/web.xml and then rebuild to give you a customised WAR for your environment.

What did the error messages say?

**Comment by blpraveen** [comment]
I need to check if this works. I will try it and get back to you.

Thanks

**Comment by blpraveen** [comment]
I could not get away with it.I am trying to run  bootstrap 
java -jar webapps\qtiworks-engine-manager.jar bootstrap -config etc\qtiworks-deployment.properties

Bellow show the  errors displayed on  the console

And also how do I change the qtiWorksDeploymentPropertiesUri  path ~/etc/qtiworks-deployment.properties in qtiworks.xml. Does it needs to unpack qtiworks-engine.war and edit the xml file?

directory strucctory looks like this
demo-base
---etc/ qtiworks-deployment.properties
---lib/
---resources
---uploads
---webapps
    |---qtiworks-engine.war
    |---qtiworks-engine-manager.jar


``
Exception in thread "main" org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'servicesConfiguration': Injection of resource
 dependencies failed; nested exception is org.springframework.beans.factory.Bean
CreationException: Error creating bean with name 'qtiWorksDeploymentSettings': I
njection of autowired dependencies failed; nested exception is org.springframewo
rk.beans.factory.BeanCreationException: Could not autowire field: private java.l
ang.String uk.ac.ed.ph.qtiworks.config.beans.QtiWorksDeploymentSettings.hibernat
eDialect; nested exception is java.lang.IllegalArgumentException: Could not reso
lve placeholder 'qtiworks.hibernate.dialect' in string value "${qtiworks.hiberna
te.dialect}"
        at org.springframework.context.annotation.CommonAnnotationBeanPostProces
sor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:307)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1147)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iateUsingFactoryMethod(ConstructorResolver.java:377)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:10
56)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:952)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:195)
        at org.springframework.context.support.AbstractApplicationContext.regist
erBeanPostProcessors(AbstractApplicationContext.java:741)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:464)
        at uk.ac.ed.ph.qtiworks.manager.QtiWorksEngineManager.performAction(QtiW
orksEngineManager.java:169)
        at uk.ac.ed.ph.qtiworks.manager.QtiWorksEngineManager.run(QtiWorksEngine
Manager.java:230)
        at uk.ac.ed.ph.qtiworks.manager.QtiWorksEngineManager.main(QtiWorksEngin
eManager.java:265)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'qtiWorksDeploymentSettings': Injection of autowired dependenc
ies failed; nested exception is org.springframework.beans.factory.BeanCreationEx
ception: Could not autowire field: private java.lang.String uk.ac.ed.ph.qtiworks
.config.beans.QtiWorksDeploymentSettings.hibernateDialect; nested exception is j
ava.lang.IllegalArgumentException: Could not resolve placeholder 'qtiworks.hiber
nate.dialect' in string value "${qtiworks.hibernate.dialect}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
:289)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1147)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:195)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProces
sor.autowireResource(CommonAnnotationBeanPostProcessor.java:445)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProces
sor.getResource(CommonAnnotationBeanPostProcessor.java:419)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProces
sor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:5
47)
        at org.springframework.beans.factory.annotation.InjectionMetadata$Inject
edElement.inject(InjectionMetadata.java:155)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject
(InjectionMetadata.java:87)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProces
sor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:304)
        ... 21 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not au
towire field: private java.lang.String uk.ac.ed.ph.qtiworks.config.beans.QtiWork
sDeploymentSettings.hibernateDialect; nested exception is java.lang.IllegalArgum
entException: Could not resolve placeholder 'qtiworks.hibernate.dialect' in stri
ng value "${qtiworks.hibernate.dialect}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
ava:517)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject
(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
:286)
        ... 34 more
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'qt
iworks.hibernate.dialect' in string value "${qtiworks.hibernate.dialect}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(P
ropertyPlaceholderHelper.java:173)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholder
s(PropertyPlaceholderHelper.java:125)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceh
olders(AbstractPropertyResolver.java:180)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequired
Placeholders(AbstractPropertyResolver.java:145)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigu
rer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:167)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolve
EmbeddedValue(AbstractBeanFactory.java:764)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
doResolveDependency(DefaultListableBeanFactory.java:785)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
resolveDependency(DefaultListableBeanFactory.java:775)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
ava:489)
``

**Comment by davemckain** [comment]
Hi,

For the bootstrap problem, the error message complains about the qtiworks.hibernate.dialect property not being set. Can I check that you uncommented (or otherwise initiialised) the database configuration stuff listed under '1. Database configuration' as described in the default/sample properties file? If you're using MySQL or PostgreSQL, you just need to uncomment one of the configs provided. Otherwise you'd want to add your own config, using the the examples for guidance.

I'll follow up on the Jetty situation once you've got past the bootstrap step.

**Comment by davemckain** [comment]
This page might be of help for configuring Jetty:

http://www.eclipse.org/jetty/documentation/current/configuring-specific-webapp-deployment.html

In particular, the following might work inside a Jetty deployment XML file for setting the necessary context params:

  ...
  <Get name="ServletContext">
     <Call name="setInitParameter">
       <Arg>qtiWorksDeploymentPropertiesUri</Arg>
       <Arg>file:/path/to/your/qtiworks-deployment.properties</Arg>
    </Call>
  </Get>
  ....

If you can't get this to work at all, you could expand the qitworks.war webapp out, and then to edit WEB-INF/web.xml to add in:

...
<context-param>
  <param-name>qtiWorksDeploymentPropertiesUri</param-name>
  <param-value>file:/path/to/your/qtiworks-deployment.properties</param-value>
</context-param>
...

This approach is less ideal though. as you have to manually edit one of the files generated by the build process. But if you're just looking to run QTIWorks rather than work on the source, it might be tolerable!

Note that in both cases, you need to specify the location of your config file as a file URI.

Hope that helps a bit!

Cheers,
David

**Comment by blpraveen** [comment]
Thanks.

Jetty started with qtiengine  with a error on browser. What I miss here again? 
Error 404 - Not Found
"No context on this server matched or handled this request"

**Comment by davemckain** [comment]
Which URL did you try after you deployed the webapp?

Assuming you have correctly set your context path as /qtiworks, then you should expect to see the QTIWorks intro page at http://localhost:8080/qtiworks

However, I do wonder whether you've put your jetty-web.xml in the correct place. The page you linked to says to put it under the WEB-INF directory inside the webapp. (You should find a file called web.xml in here too.)

Which version of Jetty are you running? Can you see any relevant messags in the log files?

**Comment by davemckain** [comment]
Closing this one as it has been dormant for a while and does not appear to be more of a deployment-related problem rather than a bug.
